### cadastrar pet
POST http://localhost:8888/api/v1/pets/register
Content-Type: application/json

{
  "nome": "Max",
  "especie": "Cachorro",
  "raca": "Golden Retriever",
  "sexo": "MACHO",
  "dataNascimento": "2020-01-01",
  "tutorId": 1
}


