### Meus detalhes
GET http://localhost:8888/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjYXJvbGluYXZlcmFkZXBhdWxhQG5vdmFkZWxpdmVyaS5jb20uYnIiLCJpYXQiOjE3MTcxMTE1NTUsImV4cCI6MTcxNzE5Nzk1NX0.hvpBtwldaSoThvdvhzEMyMxdkVauDTOE7t4I0BsSIemfNP-uQXkZ1JEURisa9tmQ


### Listar detalhes dos usuários cadastrados - 'ADMIN'
GET http://localhost:8888/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjYXJvbGluYXZlcmFkZXBhdWxhQG5vdmFkZWxpdmVyaS5jb20uYnIiLCJpYXQiOjE3MTcxMTE1NTUsImV4cCI6MTcxNzE5Nzk1NX0.hvpBtwldaSoThvdvhzEMyMxdkVauDTOE7t4I0BsSIemfNP-uQXkZ1JEURisa9tmQ

###

