server:
  port: 8888
  servlet:
    context-path: /api/v1

spring:
  application:
    name: petconnect
  banner:
    location: classpath:banner.txt
    charset: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/petconnect?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update # validate
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false
  #    url: jdbc:mysql://localhost:3306/petconnect?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
  #    user: root
  #    password: root
  #    group: true
  #    locations: filesystem:src/main/resources/db/migration
  #    sql-migration-prefix: V
  #    sql-migration-separator: __
  #    sql-migration-suffixes: .sql
  jackson:
    date-format: "dd/MM/yyyy HH:mm:ss"
    locale: 'pt-BR'
    time-zone: 'America/Sao_Paulo'
    default-property-inclusion: NON_NULL
  messages:
    basename: messages
    fallback-to-system-locale: false
    encoding: UTF-8
  mvc:
    locale:
      default-locale: pt

security:
  jwt:
    secret-key: '05955a2232d7f31a0a9879c9233e661f6e2923d5334ec67b7a64c79911407afc'
    expiration-time: 86400000

logging:
  file:
    name: petconnect.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'
  level:
    org.springframework.boot: DEBUG
    br.com.finalproject.petconnect: INFO

sentry:
  dsn: https://86e6ca7ed91c054b8d9e214f51e5460f@o4507323182809088.ingest.de.sentry.io/4507323185037392
  # Defina traces_sample_rate como 1,0 para capturar 100% das transações para monitoramento de desempenho.
  tracesSampleRate: 1.0
  exception-resolver-order: -2147483647
