server:
  port: 8888
  servlet:
    context-path: /api/v1

spring:
  application:
    name: petconnect
  banner:
    location: classpath:banner.txt
    charset: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/petconnect?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update # validate
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    locale: 'pt-BR'
    time-zone: 'America/Sao_Paulo'
    default-property-inclusion: NON_NULL
  messages:
    basename: messages
    fallback-to-system-locale: false
    encoding: UTF-8
  mvc:
    locale:
      default-locale: pt
    format:
      date: 'dd/MM/yyyy'
      time: 'HH:mm'
      date-time: 'yyyy-MM-dd HH:mm'
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'petshop.petconnect@gmail.com'
    password: 'zrgh nfow yzlb eext'
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          from: 'petshop.petconnect@gmail.com'
  data:
    web:
      pageable:
        # Define o tamanho padrão da página se não for especificado na solicitação.
        default-page-size: 20 # número padrão de itens por página
        # Define o tamanho máximo permitido para uma página.
        max-page-size: 100 # número máximo de itens por página
        # Define se a numeração das páginas começa em 1 ao invés de 0.
        one-indexed-parameters: false # se verdadeiro, páginas começam em 1 ao invés de 0
        # Define o número padrão da página inicial.
        default-page-number: 0 # número padrão de página inicial (geralmente 0)
        sort:
          # Define o nome do parâmetro na URL usado para ordenação.
          sort-parameter: sort # parâmetro de ordenação na URL

springdoc:
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  show-actuator: true
  use-management-port: true
  override-with-generic-response: true # adiciona @RestControllerAdvice
  cache:
    disabled: false # desabilita o chace springdoc-openapi
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    csrf:
      enabled: false # evitar o suporte CSRF
      use-local-storage: false # obter o token CSRF do armazenamento local
      use-session-storage: false # obter o token CSRF do Session Storage
      cookie-name: 'XSRF-TOKEN' # opcional - define o nome do Cookie CSRF
      header-name: 'X-XSRF-TOKEN' # opcional - define o nome do cabeçalho CSRF

mail:
  from:
    name: 'PetConnect'

security:
  jwt:
    secret-key: '05955a2232d7f31a0a9879c9233e661f6e2923d5334ec67b7a64c79911407afc'
    expiration-time: 86400000

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: petconnect.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'
  level:
    web: DEBUG
    org.springframework.boot: DEBUG
    br.com.finalproject.petconnect: INFO
