server:
  port: 8888
  servlet:
    context-path: /api/v1

spring:
  application:
    name: petconnect
  devtools:
    add-properties: false
  banner:
    location: classpath:banner.txt
    charset: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/petconnect?createDatabaseIfNotExist=true&requireSSL=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update # validate
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    locale: 'pt-BR'
    time-zone: 'America/Sao_Paulo'
    default-property-inclusion: NON_NULL
  messages:
    basename: messages
    fallback-to-system-locale: false
    encoding: UTF-8
  mvc:
    locale:
      default-locale: pt
    format:
      date-time: 'yyyy-MM-dd HH:mm'
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'petshop.petconnect@gmail.com'
    password: 'zrgh nfow yzlb eext'
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          from: 'petshop.petconnect@gmail.com'
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: false
        default-page-number: 0
        sort:
          sort-parameter: sort
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: false
      client:
        default-config:
          connect-timeout: 5000

springdoc:
  default-consumes-media-type: '*/*'
  default-produces-media-type: '*/*'
  show-actuator: true
  use-management-port: true
  override-with-generic-response: true
  cache:
    disabled: false
  api-docs:
    path: /api-docs
    version: OPENAPI_3_0
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    csrf:
      enabled: false
      use-local-storage: false
      use-session-storage: false
      cookie-name: 'XSRF-TOKEN'
      header-name: 'X-XSRF-TOKEN'

mail:
  from:
    name: 'PetConnect'

security:
  jwt:
    secret-key: '05955a2232d7f31a0a9879c9233e661f6e2923d5334ec67b7a64c79911407afc'
    expiration-time: 86400000

feign:
  name: 'viacep-api'
  url: 'https://viacep.com.br/ws'

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: petconnect.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'
  level:
    web: DEBUG
    org.springframework.boot: DEBUG
    br.com.finalproject.petconnect: INFO

