###
# @name actuator
GET http://localhost:8888/api/petconnet/actuator

###
# @name beans
GET http://localhost:8888/api/petconnet/actuator/beans

###
# @name health
GET http://localhost:8888/api/petconnet/actuator/health

###
# @name metrics
GET http://localhost:8888/api/petconnet/actuator/metrics

###
# @name mappings
GET http://localhost:8888/api/petconnet/actuator/mappings

### .
# @name caches
GET http://localhost:8888/api/petconnet/actuator/caches

###
# @name info
GET http://localhost:8888/api/petconnet/actuator/info

###
# @name conditions
GET http://localhost:8888/api/petconnet/actuator/conditions

###
# @name configprops
GET http://localhost:8888/api/petconnet/actuator/configprops

###
# @name env
GET http://localhost:8888/api/petconnet/actuator/env

###
# @name loggers
GET http://localhost:8888/api/petconnet/actuator/loggers

###
# @name heapdump
GET http://localhost:8888/api/petconnet/actuator/heapdump

###
# @name threaddump
GET http://localhost:8888/api/petconnet/actuator/threaddump

###
# @name scheduledtasks
GET http://localhost:8888/api/petconnet/actuator/scheduledtasks