### cadastrando animal
# @name registerPet
POST http://localhost:8888/api/petconnet/pets/register
Content-Type: application/json

{
  "name": "Pandora",
  "type": "cachorro",
  "age": 2,
  "raca": "N/A"
}

### listando animais cadastrados
# @name listPets
GET http://localhost:8888/api/petconnet/pets/list
Content-Type: application/json

### buscando animal por ID
# @name getPetById
GET http://localhost:8888/api/petconnet/pets/4
Content-Type: application/json

### atualizando animal por ID
# @name updatePetById
PUT http://localhost:8888/api/petconnet/pets/5
Content-Type: application/json

{
  "name": "Suzi",
  "type": "gato",
  "age": 4,
  "raca": "N/A",
  "user": 1
}

### excluindo animal por ID
# @name deletePetById
DELETE http://localhost:8888/api/petconnet/pets/3
Content-Type: application/json