### Register Pet
POST http://localhost:8888/api/petconnet/pets/register
Content-Type: application/json

{
  "name": "Rian",
  "age": 5,
  "breed": "N/A",
  "color": "Preto",
  "animal_type": "cat"
}

### Search Pet By ID
GET http://localhost:8888/api/petconnet/pets/search/2

### List All Pets
GET http://localhost:8888/api/petconnet/pets/list

### Remove Pet By ID
DELETE http://localhost:8888/api/petconnet/pets/1

### Register Pet
PUT http://localhost:8888/api/petconnet/pets/2
Content-Type: application/json

{
  "name": "Rian",
  "age": 5,
  "breed": "N/A",
  "color": "Preto",
  "animal_type": "cat"
}