### Cadastrar usuário
POST http://localhost:8888/api/petconnet/users/register
Content-Type: application/json

{
  "username": "mirella.gabrielly.darocha@jmmarcenaria.com.br",
  "name": "Mirella Gabrielly da Rocha",
  "phone_number": "83987881658",
  "document_number": "83747383408",
  "password": "Ju1!@n36"
}

### Buscar usuário por ID /{id}
GET http://localhost:8888/api/petconnet/users/1
Content-Type: application/json

### Buscar Usuário por Username /search/username/{username}
GET http://localhost:8888/api/petconnet/users/search/username/julianevaliati@email.com
Content-Type: application/json

### Listar Todos os Usuários /list
GET http://localhost:8888/api/petconnet/users/list
Content-Type: application/json

### Atualizar usuário
PUT http://localhost:8888/api/petconnet/users/3
Content-Type: application/json

{
  "username": "mirella.gabrielly.darocha@jmmarcenaria.com.br",
  "name": "Mirella Gabrielly da Rocha",
  "phone_number": "83987881658",
  "document_number": "83747383408"
}

### Desativar usuário
POST http://localhost:8888/api/petconnet/users/1/disable

### Ativar usuário
POST http://localhost:8888/api/petconnet/users/2/activate