### Cadastrar usuário
POST http://localhost:8888/api/v1/users/register
Content-Type: application/json

{
  "username": "mirella.gabrielly.darocha@jmmarcenaria.com.br",
  "name": "Mirella Gabrielly da Rocha",
  "documentNumber": "83747383408",
  "password": "Ju1!@n36"
}

### Buscar usuário por ID /{id}
GET http://localhost:8888/api/v1/users/1
Content-Type: application/json

### Buscar Usuário por Username /search/username/{username}
GET http://localhost:8888/api/v1/users/search/username/julianevaliati@email.com
Content-Type: application/json

### Listar Todos os Usuários /list
GET http://localhost:8888/api/v1/users/list
Content-Type: application/json

### Atualizar usuário
PUT http://localhost:8888/api/v1/users/1
Content-Type: application/json

{
  "id": 1,
  "username": "mirella.gabrielly.darocha@jmmarcenaria.com.br",
  "name": "Mirella Gabrielly da Rocha",
  "documentNumber": "83747383408"
}

### Desativar usuário
POST http://localhost:8888/api/v1/users/1/disable

### Ativar usuário
POST http://localhost:8888/api/v1/users/2/activate

### Buscar usuário e listar seus pets
GET http://localhost:8888/api/v1/users/1/pets
Content-Type: application/json

### Login
POST http://localhost:8888/api/v1/login
Content-Type: application/json

{
  "username": "julianemaran@gmail.com",
  "password": "Ju1!@n36"
}

###

