openapi: 3.0.3
info:
  title: API REST Users
  description: API REST Users
  version: 1.0.0
servers:
  - url: 'http://localhost:8082/api/petconnet/users'
tags:
  - name: users
    description: Usuários
paths:
  /{id}/pets:
    get:
      summary: 'Buscar usuário por ID e listar os pets cadastrados'
      description: 'Buscar usuário por ID e listar os pets cadastrados'
      tags:
        - users
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: Identificador único do Usuário
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'Dados do usuário solicitado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResponse'
        '404':
          description: 'Usuário não encontrado.'
        '500':
          description: 'Ocorreu um erro inesperado no servidor. Tente novamente mais tarde.'
components:
  schemas:
    UserListResponse:
      description: 'Retorna os dados do usuário cadastrado.'
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 'Mirella Gabrielly da Rocha'
        pets:
          type: array
          items:
            $ref: '#/components/schemas/PetListResponse'
    PetListResponse:
      description: 'Dados que o usuário pode atualizar'
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2
        name:
          type: string
          example: 'Rex'
        color:
          type: string
          example: 'Golden'
        breed:
          type: string
          example: 'Golden Retriever'
        animalType:
          type: string
          example: 'Dog'
        birthdate:
          type: string
          format: date-time
          example: '31/12/2020'
        createAt:
          type: string
          format: date-time
          example: '2024-04-15T13:15:39'
        updatedAt:
          type: string
          format: date-time
          example: '2024-04-15T13:15:39'
    ErrorReseponse:
      description: "Payload de saída - response"
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: '2024-03-26T12:24:23.666+00:00'
        status:
          type: integer
          format: int32
          example: 500
        error:
          type: string
          example: 'Internal Server Error'
        message:
          type: string
          example: 'Erro interno no servidor. Tente novamente mais tarde.'