name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Azure Container Registry
        run: echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login ${{ secrets.AZURE_ACR_NAME }}.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/petconnect:latest .

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/petconnect:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/petconnect:latest

      - name: Configure Azure Web App Environment Variables
        run: |
          az webapp config appsettings set --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings \
            SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/petconnect?createDatabaseIfNotExist=true\&serverTimezone=UTC \
            SPRING_DATASOURCE_USERNAME=root \
            SPRING_DATASOURCE_PASSWORD=root
